# Generated by Django 5.1.3 on 2024-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarungo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - 最優先'), (2, '2 - 高'), (3, '3 - 中'), (4, '4 - 低'), (5, '5 - 最低')], default=3),
        ),
    ]
