# Generated by Django 5.1.3 on 2024-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarungo', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, '1 - 最優先'), (2, '2 - 高'), (3, '3 - 中'), (4, '4 - 低'), (5, '5 - 最低')], default=3, null=True),
        ),
    ]
