# Generated by Django 5.1.4 on 2025-01-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarungo', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
