# Generated by Django 5.1.4 on 2025-01-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarungo', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '低い'), (5, '普通'), (10, '高い')], default=5),
        ),
    ]
