version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: yarungo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yarungo
      MYSQL_USER: saburi314
      MYSQL_PASSWORD: saburi314_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yarungo_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yarungo_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - yarungo_network

  nginx:
    image: nginx:latest
    container_name: yarungo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 環境に応じて切り替え
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${SSL_CERT_PATH}/fullchain.pem:/etc/ssl/private/fullchain.pem:ro
      - ${SSL_CERT_PATH}/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - web
    networks:
      - yarungo_network

volumes:
  db_data:

networks:
  yarungo_network:
    driver: bridge
