version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: yarungo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yarungo
      MYSQL_USER: saburi314
      MYSQL_PASSWORD: saburi314_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: yarungo_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/yarungo"

volumes:
  db_data:
